const $=id=>document.getElementById(id);const qs=s=>document.querySelector(s);const page=document.body?.dataset?.page||'home';const fmt=size=>size<1024?`${size} B`:size<1048576?`${(size/1024).toFixed(1)} KB`:`${(size/1048576).toFixed(1)} MB`;const getRoom=()=>sessionStorage.getItem('droppoint-room')||'';const setRoom=v=>sessionStorage.setItem('droppoint-room',v);let socket=null,room=getRoom(),files=[];
function wsUrl(){return `${location.protocol==='https:'?'wss':'ws'}://${location.host}`}function setStatus(t,on){const e=$('status');if(!e)return;e.innerHTML=`<span class="status-dot"></span> ${t}`;e.className=`status ${on?'on':'off'}`}function notice(t,k='info'){const e=$('roomStatus')||$('connectNotice');if(e){e.className=`notice ${k}`;e.textContent=t}}function go(p){location.href=p}function parsed(v){try{return JSON.parse(v)}catch{return null}}
function applyRoomResult(joined){const result=$('roomResult');if(!result)return;if(joined){result.classList.add('hidden');return}result.classList.remove('hidden');if($('roomCode'))$('roomCode').textContent=room;if($('roomResultLabel'))$('roomResultLabel').textContent='ODA KODUN';if($('copyRoom'))$('copyRoom').classList.remove('hidden');if($('roomResultText'))$('roomResultText').textContent='Bu kodu diğer cihazdaki kişiye gönder. Sonra içeriğe geçebilirsin.';if($('continueRoom'))$('continueRoom').textContent='İçeriğe geç'}
function connectSignal(){if(socket&&socket.readyState<=WebSocket.OPEN)return Promise.resolve();return new Promise((resolve,reject)=>{socket=new WebSocket(wsUrl());socket.onopen=()=>{setStatus('Sunucu hazır',true);resolve()};socket.onerror=()=>{setStatus('Bağlantı hatası',false);notice('Sunucuya bağlanılamadı.','error');reject(new Error('websocket'))};socket.onclose=()=>setStatus('Sunucu bağlantısı kapandı',false);socket.onmessage=e=>{const m=parsed(e.data);if(!m)return;if(m.type==='item-added'&&page==='transfer'){addItem(m.item);return}if((m.type==='created'||m.type==='joined')&&page==='room'){room=m.room;setRoom(room);if(m.type==='joined'){go('choose.html');return}applyRoomResult(false);notice('Oda hazır. Kodunu diğer cihazla paylaş.','success')}if(m.type==='error')notice(m.message||'Bir hata oluştu.','error')}})}
async function createRoom(){try{await connectSignal();socket.send(JSON.stringify({type:'create'}))}catch{}}async function joinRoom(){const code=$('roomInput')?.value.trim().toUpperCase()||'';if(!/^[A-Z0-9]{6}$/.test(code)){notice('6 haneli oda kodunu gir.','error');return}try{await connectSignal();socket.send(JSON.stringify({type:'join',room:code}))}catch{}}
async function initRoom(){$('create')?.addEventListener('click',createRoom);$('join')?.addEventListener('click',joinRoom);$('roomInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')joinRoom()});$('copyRoom')?.addEventListener('click',async()=>{await navigator.clipboard.writeText(room);$('copyRoom').textContent='Kopyalandı';setTimeout(()=>$('copyRoom').textContent='Kodu kopyala',1400)});await connectSignal().catch(()=>{})}
function initChoose(){if(!room){go('room.html');return}if($('currentRoom'))$('currentRoom').textContent=room}
function addItem(item){const box=$('received');if(!box)return;if(box.querySelector('.muted'))box.innerHTML='';if(document.querySelector(`[data-item="${item.id}"]`))return;const row=document.createElement('article');row.className='received-item';row.dataset.item=item.id;const body=document.createElement('div');body.innerHTML='<b></b><p></p>';if(item.kind==='file'){body.querySelector('b').textContent=item.name;body.querySelector('p').textContent=fmt(item.size);row.appendChild(body);const a=document.createElement('a');a.className='m3-btn tonal small';a.href=`/api/rooms/${encodeURIComponent(room)}/files/${encodeURIComponent(item.id)}`;a.download=item.name;a.textContent='İndir';row.appendChild(a)}else{body.querySelector('b').textContent='Metin';body.querySelector('p').textContent=item.text;row.appendChild(body);const b=document.createElement('button');b.className='m3-btn tonal small';b.textContent='Kopyala';b.onclick=()=>navigator.clipboard.writeText(item.text);row.appendChild(b)}box.prepend(row)}
async function refreshItems(){const r=await fetch(`/api/rooms/${encodeURIComponent(room)}/items`);if(!r.ok)throw new Error('Oda bulunamadı');const data=await r.json();data.items.forEach(addItem)}
async function uploadText(){const text=$('text')?.value.trim()||'';if(!text)return;const r=await fetch(`/api/rooms/${encodeURIComponent(room)}/text`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Metin gönderilemedi');$('text').value='';$('text').dispatchEvent(new Event('input'));addItem(data.item);notice('Metin odaya eklendi.','success')}
function renderFiles(){const list=$('fileList');if(!list)return;list.innerHTML='';for(const f of files){const t=$('fileItem').content.cloneNode(true);t.querySelector('b').textContent=f.name;t.querySelector('small').textContent=fmt(f.size);list.appendChild(t)}}
async function uploadFiles(){if(!files.length)return;const button=$('sendFile');if(button)button.disabled=true;try{for(const file of files){const r=await fetch(`/api/rooms/${encodeURIComponent(room)}/files`,{method:'POST',headers:{'Content-Type':file.type||'application/octet-stream','X-File-Name':encodeURIComponent(file.name)},body:file});const data=await r.json();if(!r.ok)throw new Error(data.error||`${file.name} yüklenemedi`);addItem(data.item)}files=[];if($('file'))$('file').value='';renderFiles();notice('Dosyalar odaya eklendi.','success')}finally{updateButtons()}}
function updateButtons(){if($('sendFile'))$('sendFile').disabled=!files.length;if($('sendText'))$('sendText').disabled=!$('text')?.value.trim()}
async function initTransfer(){if(!room){go('room.html');return}const type=new URLSearchParams(location.search).get('type')||'file';if($('transferRoom'))$('transferRoom').textContent=room;if($('transferTitle'))$('transferTitle').textContent=type==='file'?'Dosya gönder':'Metin gönder';if($('transferLead'))$('transferLead').textContent=type==='file'?'Dosyayı odaya ekle; diğer cihaz geldiğinde indirebilir.':'Metni odaya ekle; diğer cihaz geldiğinde görebilir.';$(type==='file'?'filePanel':'textPanel')?.classList.remove('hidden');await connectSignal().catch(()=>{});if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify({type:'join',room}));await refreshItems().catch(()=>{});if($('file')){$('file').onchange=()=>{files=[...$('file').files];renderFiles();updateButtons()};const drop=qs('.drop');if(drop){['dragenter','dragover'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>{files=[...e.dataTransfer.files];renderFiles();updateButtons()})}}if($('text'))$('text').addEventListener('input',()=>{$('count').textContent=`${$('text').value.length.toLocaleString('tr-TR')} / 20.000`;updateButtons()});$('sendText')?.addEventListener('click',()=>uploadText().catch(e=>notice(e.message,'error')));$('sendFile')?.addEventListener('click',()=>uploadFiles().catch(e=>notice(e.message,'error')));$('newRoom')?.addEventListener('click',()=>{sessionStorage.removeItem('droppoint-room');go('room.html')})}
if(page==='room')initRoom();else if(page==='choose')initChoose();else if(page==='transfer')initTransfer();